### PR TITLE
Tiny Fixes

### PR DESCRIPTION
**Pull request by pitis91**
Added temple of equilibrium vines script (just missing to add my map).
Fixed ruthless seven corpse bosses.
Fixed Nina's Body.
Added transcripts to Nina.
Fixed servant sentry help words (missing to add timer to each 24 o 20h
return to give the slime gobbler).
Removed message from ungreez creaturescript.
Removed new frontier secured exit from minotaur (missing to remove from
map just adding my work).
Removed pits of inferno message on each shortcut.
added level restriction to gearwheel chain

### CODE REVIEW

**Comment by ranisalt** [comment]
Why didn't you made a single commit for every change? If something goes wrong in your big single commit, there's a lot of work to redo after reverting the commit ._.

**Comment by pitis91** [comment]
I was made 1 commit for each file I was made 1 pull for each file i was made all and now you answer me that? shit fuck that if you have anything non rl, find it and do it by yourself ;)

**Comment by ranisalt** [comment]
Whoa we got a badass over here. Sorry, GitHub's pull request system has fooled me, I didn't see one of the commits was a collection of various commits. I'm not even this repo's owner, lol, measure your words please.

@ninjalulz can you seek through his changes and redo what he has deleted if it's useful? Seems to have lots of stuff in this PR.

**Comment by bigharry1991** [comment]
island of destiny npcs dont work

**Pull request closed without merging**
