### PR TITLE
Added Knight leaders

### PR DESCRIPTION
**Pull request by EPuncker**
ref #61

### CODE REVIEW

**Comment by EPuncker** [comment]
@ninjalulz ninja? xD

**Comment by ninjalulz** [comment]
Move addSpellKeyword to KeywordHandler

```Lua
-- Adds a keyword which acts as a spell word
function KeywordHandler:addSpellKeyword(keys, parameters, condition, action)
	local keys = keys
	keys.callback = FocusModule.messageMatcherDefault

	local spellKeyword = self:addKeyword(keys, StdModule.say, {npcHandler = parameters.npcHandler, text = string.format("Do you want to learn the spell '%s' for %s?", parameters.spellName, parameters.price > 0 and parameters.price .. ' gold' or 'free')}, condition)
	spellKeyword:addChildKeyword({'yes'}, StdModule.learnSpell, {npcHandler = parameters.npcHandler, spellName = parameters.spellName, level = parameters.level, price = parameters.price}, nil, action)
	spellKeyword:addChildKeyword({'no'}, StdModule.say, {npcHandler = parameters.npcHandler, text = 'Maybe next time.', reset = true})
end
```

In the NPC file, it would look like this(?)
```Lua
keywordHandler:addSpellKeyword({'front', 'sweep'}, {npcHandler = npcHandler, spellName = 'Front Sweep', price = 4000, level = 70})
```

I'm on my phone at the moment so this might be incorrect, feel free to correct this @TheSumm xD

**Comment by EPuncker** [comment]
where is the vocation part? :P

**Comment by WibbenZ** [comment]
There are 2 arguments missing, the condition and action.
First one is the validation, level check, vocation check etc.
Second one is the function to add the spell.

**Comment by EPuncker** [comment]
@ninjalulz ? xD I want to complete this :P

**Comment by WibbenZ** [comment]
Can't you see my post? ;o
In the function call he only listed the array, not the condition and action.

**Comment by EPuncker** [comment]
I may be blind but I still don't see the vocation check part :/

**Comment by WibbenZ** [comment]
```
keywordHandler:addSpellKeyword({'front', 'sweep'}, {npcHandler = npcHandler, spellName = 'Front Sweep', price = 4000, level = 70}, function (player) return player:isDruid() end, function (player) return player:learnSpell(spellName) end)
```

Would be alot easier actually to handle the learning in the lib file, since there is no use copying that function all the time, we have all we need in the condition argument.

**Comment by ninjalulz** [comment]
I've modified my previous post.

This is how you would use this at the moment.
```Lua
keywordHandler:addSpellKeyword({'front', 'sweep'}, {npcHandler = npcHandler, spellName = 'Front Sweep', price = 4000, level = 70, vocation = 4})
```

**Comment by EPuncker** [comment]
the vocation part accept array? '1, 2'?

**Comment by EPuncker** [comment]
and shouldn't it not use the getBase to vocation since there are spells that only promoted characters can learn?

**Comment by ninjalulz** [comment]
I think the promotion part should be handled in StdModule.learnSpell, will have to check it on Tibia later.

**Comment by EPuncker** [comment]
Promoted characters can learn new spells:

Elite Knights
Challenge
Royal Paladins
Conjure Power Bolt
Elder Druids
Wild Growth
Master Sorcerers
Enchant Staff

**Comment by EPuncker** [comment]
only eremo teaches promoted characters :P

**Pull request closed without merging**
