### PR TITLE
i am not sure if 10 is the correct value but letting a cobra melee fo…

### PR DESCRIPTION
**Pull request by viperthepala**
…r 200 sure aint right.

### CODE REVIEW

**Comment by viperthepala** [comment]
In that case something else is wrong as cobras hit 100+ some times that cant be correct

**Comment by viperthepala** [comment]
P.s. Its the melee dmg so ur wrong there that value has nothing to do with its poison dmg

**Comment by viperthepala** [comment]
can you please word that different as i dont get what your trying to say.

**Comment by EPuncker** [comment]
your pull request is right, just ignore the rest :P

**Comment by Schiffers** [comment]
why my "tag" of cobra was deleted?

**Comment by Schiffers** [comment]
see again, now appears my tag, when you use </> not appears e.e

**Comment by viperthepala** [comment]
any1 that came up with a propper scripting for the cobra? as they still hit ridiculously hard.

**Comment by Schiffers** [comment]
Bro I'll tell again, see it
attack name="melee" interval="2000" skill="10" attack="5" poison="100" 
with this line resolve the problem, she will hit weak and will poison with the hit

**Comment by ninjalulz** [comment]
You might as well use:
```XML
<attack name="melee" interval="2000" min="0" max="-20" poison="100" />
```

@viperthepala Please update the value for max to -20, and poison to 100 (5hp/turn).

**Comment by viperthepala** [comment]
done

**Comment by ninjalulz** [comment]
Thanks

**Pull request merged**
