### PR TITLE
Fixes etc

### LINKED ISSUE #43: Missing special Food
<a href="https://github.com/mattyx14"></img></a> **Issue by [mattyx14](https://github.com/mattyx14)**
_Tuesday Nov 18, 2014 at 15:56 GMT_
_Originally opened as https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/1474_

----

The boosting food no are added

### PR DESCRIPTION
**Pull request by WibbenZ**
Fixed all Shimmer ~ items, #84
Fixed special foods, the "drowning" function still has to be added, we
could modify the drowning.lua script, but I don't feel like that is the
best way tbh.
Closes #43
Fixed the "random spawns" from #56
Renamed data/lib to data/library.
Added a template for the world board.
Fixed most POI bosses how ever the loot should be checked.
Fixed Empror Rehal greeting message.
Fixed most of the bugs in The Hidden City of Beregar quest.
Fixed the following bugs with the postman quest.
* Item name (itemid: 2332).
* Quest log string.
* Lower case in a message in Kevin.lua.
* Added a script to set the correct storage for the mission where you
should get Waldo's posthorn.

### CODE REVIEW

**Comment by WibbenZ** [comment]
Finally haha...

**Comment by TheSumm** [comment]
Don't rename libs to library.

**Comment by WibbenZ** [comment]
Why not rename it to library? How is libs a good name?

**Comment by Schiffers** [comment]
bug with shimmer swimmer, when you use the fish in one item the fish is removed, and the item not is removed, need put to remove the item too....
and when you use the shimmer swimmer in item have one msg white, and for last, have one magic effect "bluebublle"

**Comment by WibbenZ** [comment]
Np I understand :p Just good to get feedback about things that I have no clue about.
And tibia wikia isen't always the best resource for things like this..

The target item should also be removed?
And it should show the bubles effect on the player or on the target position?
Do you know what the text / texts are?

**Comment by Schiffers** [comment]
I don't remember the msg, but I remember that exist....
the magic effect is in the target position ... if are in bp, the effect is in player...
and the item should be removed bro,
they transform in other item
swimmer + eye of a deepling = transform to shimmer glower
the script should be like this:
target:transform(itemX)
item:remove(1)
toPosition:sendMagicEffect(CONST_ME_BLUEBUBBLE)

**Comment by WibbenZ** [comment]
Better to use addItem in case the player has the item on the floor / depot etc.
The effects name is: CONST_ME_BUBBLES.

Ill have to leave the message empty if no one else knows.

**Comment by Schiffers** [comment]
I will try with your script, if I think that can do it with transform I will put with transform, case the player have your items in a second bp or container.. 
about the bubbles, the bubbles what I say is the bubble like a bubble from shallow water when you drop item know
(sorry my bad english, i'm studying to be better)

**Comment by WibbenZ** [comment]
Your English is fine except that you rarelt use dots and you don't capitalize things haha..
Ive updated the effect and it now uses transform insted.
Gonna try and search abit on youtube and see if I can find that message.

**Comment by Schiffers** [comment]
I tryed find in youtube, but not have sucess, more easy try tibia cast :p 
I'll try tibia cast, and return with feedback

**Comment by WibbenZ** [comment]
Yeah tried youtube aswell, please do tell me if you find anything on tibia cast :)

**Comment by Schiffers** [comment]
:/ i'm sorry, I not found nothing there too...
just leave how is now ...
when we found we fix :3

**Comment by WibbenZ** [comment]
Yeah nothing major really, same with the special foods. Left them blank so we when someone sees it they will know some of the messages are empty.
Foods might be easier to find if someone has done the quest and wanted to test them idk haha :p 
Alot bigger things to worry about then things like this tbh.

**Comment by Schiffers** [comment]
yes, we need for now track the world changes ...
about the world changes I have the spirit gate place, don't know if have in the map of project...
if not I share...

**Comment by WibbenZ** [comment]
@ninjalulz @TheSumm Any news?

**Comment by TheSumm** [comment]
Revert the name change of libs folder, also I do not see the change of Kevin.lua which is stated in the commit message.

If you squash the commits I can then take a look on all changes again.

**Comment by WibbenZ** [comment]
Okay ive reverted that and added Kevin again.
Do you know how I rebase it in the github client? Can't get the shell to work for me.

**Pull request closed without merging**
