### PR TITLE
Update inquisitionQuestUngreez.lua

### PR DESCRIPTION
**Pull request by pitis91**
on real tibia don't appear if you have killed ungreez or not "any message".

### CODE REVIEW

**Comment by EPuncker** [comment]
:+1:

**Comment by pitis91** [comment]
one question, are you thinking to add something that I've posted like my map, actions or something? just to continue working and going there to share it or work for me and start working in oramond

**Comment by ninjalulz** [comment]
Would be great if you submitted a single pull request instead of 8. You can achieve this by either using git bash or git client (easier for beginners(?)).

**Comment by pitis91** [comment]
I only know how to do this type of pulls I want to know how to share more than 1 change at the same time but idk how :/

**Comment by EPuncker** [comment]
https://otland.net/threads/contributing-to-someones-repository-create-a-pull-request-on-github.210627/

**Comment by pitis91** [comment]
oh thanks I  gona take a look! I hope to learn, just another question friend, are you working on your actual map? because I've uploaded my fixed map on a issue but I still working today on the map is just the same but I'm adding the guildhouses depots if you want I can upload it again.

**Comment by EPuncker** [comment]
better upload it again

**Comment by pitis91** [comment]
ok mate where do you preffer to I copy the link there or in same location as the last map?

**Comment by EPuncker** [comment]
idk, @ninjalulz is the one in the job to check it now, and since we don't have that topic about map anymore, I don't know xD

**Comment by pitis91** [comment]
I installed github on windows but it don't solve how to pull more than 1 files and that otland is the same to me.
what problem is it to change file by file?

**Comment by pitis91** [comment]
#165 map uploaded

**Comment by ninjalulz** [comment]
The problem is the amount of pull requests (a lot of commits), Sure, I could go in afterwards and squash the commits but I would rather see that you and others learn how to use git properly.

**Comment by pitis91** [comment]
thanks man I just learn something today :D

**Pull request closed without merging**
